version: '3.8'
name: user-journal-microservice-project

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: uroot
      MYSQL_PASSWORD: proot
    ports:
      - "3307:3306"
    volumes:
      - userdb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-journal:
    image: mongo:latest
    container_name: mongodb-journal
    restart: always
    ports:
      - "27018:27017"
    environment:
      DB_URI: mongodb://root:rootpassword@mongodb-journal:27017/journaldb?authSource=admin
    volumes:
      - journaldb-data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    restart: always
    depends_on:
      - mysql-user
      - kafka
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://mysql-user:3306/userdb
      DB_USERNAME: root
      DB_PASSWORD: root
      HIBERNATE_FORMAT_SQL: true
      SHOW_SQL: false
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_USER_CREATED: user-events
      TOPIC_USER_FAILED: user-operation-failed
      JWT_SECRET: w3nFB9T2zYlT5hUvDdDmcJ9U7NfFcEYbAKtqucCiwgKaVZTjhS3lmA3FlCJeJXJf
      JWT_EXPIRATION: 3600000

  journal-service:
    build:
      context: ./journal-service
      dockerfile: ./Dockerfile
    container_name: journal-service
    restart: always
    depends_on:
      - mongodb-journal
      - kafka
      - user-service
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      DB_URI: mongodb://mongodb-journal:27017/journalservice
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: journal-service-group
      TOPIC_USER_CREATED: user-events
      TOPIC_USER_FAILED: user-operation-failed
      JWT_SECRET: w3nFB9T2zYlT5hUvDdDmcJ9U7NfFcEYbAKtqucCiwgKaVZTjhS3lmA3FlCJeJXJf
      JWT_EXPIRATION: 3600000
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123

volumes:
  userdb-data:
  journaldb-data:
